#pragma once

#include <vulkan/vulkan.h>
//#include <GLFW/glfw3.h>
#include <assert.h>
#include <tuple>
#include <vector>
#include <string>

#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_ENABLE_EXPERIMENTAL
/*
The perspective projection matrix generated by GLM will use the OpenGL depth range of - 1.0 to 1.0 by default.
We need to configure it to use the Vulkan range of 0.0 to 1.0 using the GLM_FORCE_DEPTH_ZERO_TO_ONE definition.
*/
#include <glm/glm.hpp>
#include <glm/gtx/transform.hpp>


#define Vec4ToVec3(a) glm::vec3(a.x, a.y, a.z)
#define Vec3ToVec4_1(a) glm::vec4(a.x, a.y, a.z, 1.0f)
#define Vec3ToVec4_0(a) glm::vec4(a.x, a.y, a.z, 0.0f)


void ErrorCheck(VkResult result);

size_t GetMemoryAlignedDataSizeForBuffer(const VkPhysicalDevice& device, const size_t& dataSize);


VkCommandBuffer AllocateCommandBuffer(
    const VkDevice& device,
    const VkCommandPool& commandPool
);

void FreeCommandBuffer(
    const VkDevice& device,
    const VkCommandPool& commandPool,
    VkCommandBuffer* commandBuffer
);

VkDeviceMemory AllocateHostCoherentMemory(
    const VkPhysicalDevice& physicalDevice,
    const VkDevice& device,
    const VkDeviceSize& bufferSize,
    const VkMemoryRequirements& memoryRequirements
);

std::tuple<VkBuffer, VkDeviceMemory> LoadImageDataIntoStagingBuffer(
    const VkPhysicalDevice& physicalDevice,
    const VkDevice& device,
    const unsigned char* data, const size_t& dataSize
);


// Load an image from a file, and copy it into a newly created buffer (backed with memory already):
// Returns a tuple with: <0> the buffer handle, <1> the memory handle, <2> width, <3> height
std::tuple<VkBuffer, VkDeviceMemory, int, int> LoadImageIntoHostCoherentMemory(
    const VkPhysicalDevice& physicalDevice,
    const VkDevice& device,
    const std::string& pathToImageFile
);

// Free memory that has been allocated with AllocateHostCoherentMemoryForBuffer
void FreeMemory(
    const VkDevice& device,
    const VkDeviceMemory& memory
);

void CreateBufferAndMemory(
    const VkPhysicalDevice& physicalDevice, const VkDevice& device,
    VkBuffer& buffer, VkDeviceMemory& memory, const size_t& dataSize,
    const VkBufferUsageFlags& usage, const VkMemoryPropertyFlags& memProps
);

void DestroyBuffer(
    const VkDevice& device,
    const VkBuffer& buffer
);

void ChangeImageLayoutWithBarriers(
    const VkCommandBuffer& commandBuffer,
    const VkPipelineStageFlags& srcPipelineStage, const VkPipelineStageFlags& dstPipelineStage,
    const VkAccessFlags& srcAccessMask, const VkAccessFlags& dstAccessMask,
    const VkImage& image,
    const VkImageLayout& oldLayout, const VkImageLayout& newLayout
);

void CopyBufferToImage(
    const VkCommandBuffer& commandBuffer,
    const VkBuffer& buffer,
    const VkImage& image, const uint32_t width, const uint32_t height
);

std::tuple<VkImage, VkDeviceMemory> CreateImage(
    const VkDevice& device,
    const VkPhysicalDevice& physicalDevice,
    const uint32_t width, const uint32_t height,
    const VkFormat& format, const VkImageUsageFlags& usageFlags
);

// Destroy an image that has been created using the helper functions
void DestroyImage(
    const VkDevice& device,
    VkImage image
);

// Create an image view to an image
VkImageView CreateImageView(
    const VkDevice& device,
    const VkPhysicalDevice& physicalDevice,
    const VkImage& image, const VkFormat& format, const VkImageAspectFlags& imageAspectFlags
);

// Destroy an image view that has been created using the helper functions
void DestroyImageView(
    const VkDevice& device,
    VkImageView imageView
);

std::tuple<VkShaderModule, VkPipelineShaderStageCreateInfo> CreateShaderModule(
    const VkDevice& device,
    const std::string& path,
    const VkShaderStageFlagBits& shaderStage
);

void DestroyShaderModule(
    const VkDevice& device,
    VkShaderModule shaderModule
);

// Copy data of the gifen size into the buffer
void CopyDataIntoHostCoherentMemory(
    const VkDevice& device,
    const size_t& dataSize,
    const void* data,
    VkDeviceMemory& memory
);

void ChangeImageLayout(const VkDevice& device, std::vector<VkImage>& imageList, const VkQueue& queue,
    uint32_t queueFamilyIndex, VkImageLayout oldLayout, VkImageLayout newLayout);

std::tuple<VkBuffer, VkDeviceMemory> CreateStagingBuffer(uint32_t dataSize, const VkPhysicalDevice& physicalDevice, const VkDevice& device);

void CopyFromStagingBuffer(const VkBuffer& stagingBuffer, const VkBuffer& targetBuffer, uint32_t dataSize,
    const VkDevice& device, const VkQueue& queue, uint32_t queueFamilyIndex);
